Category.create! id: 1, name: "Uncategorized"
Category.create! id: 2, name: "Brake Fluid"
Category.create! id: 3, name: "Brake Cleaner"
Category.create! id: 4, name: "Chain Lube"
Category.create! id: 5, name: "Carburator Cleaner"
Category.create! id: 6, name: "Foaming Cleaner"
Category.create! id: 7, name: "Injection Cleaner"
Category.create! id: 8, name: "Penetrant"
Category.create! id: 9, name: "Coolant"
Category.create! id: 10, name: "Spray Paint"
Category.create! id: 11, name: "Purging"
Category.create! id: 12, name: "Freshener"
Category.create! id: 13, name: "Lubricant"
