Product.create! id: 1, code: 'BR50', name: 'Brake Fluid A72 50 ml', category: Category.find(2)
Product.create! id: 2, code: 'BR300', name: 'Brake Fluid A72 300 ml', category: Category.find(2)
Product.create! id: 3, code: 'BC500', name: 'Brake Cleaner A72 500 ml', category: Category.find(3)
Product.create! id: 4, code: 'CL300', name: 'Chain Lube A72 300 ml', category: Category.find(4)
Product.create! id: 5, code: 'CC300', name: 'Carburator Cleaner A72 300 ml', category: Category.find(5)
Product.create! id: 6, code: 'CC500', name: 'Carburator Cleaner A72 500 ml', category: Category.find(5)
Product.create! id: 7, code: 'FC300', name: 'Foaming Cleaner A72 300 ml', category: Category.find(6)
Product.create! id: 8, code: 'IC300', name: 'Injection Cleaner A72 300 ml', category: Category.find(7)
Product.create! id: 9, code: 'PT300', name: 'Penetrant A72 300 ml', category: Category.find(8)
Product.create! id: 10, code: 'RC1000', name: 'Radiator Coolant A72 1000 ml', category: Category.find(9)
Product.create! id: 11, code: 'SP300', name: 'Spray Paint A72 300 ml', category: Category.find(10)
Product.create! id: 12, code: 'SPF300', name: 'Spray Paint (Flourescent) A72 300 ml', category: Category.find(10)
Product.create! id: 13, code: 'SIC150', name: 'Spray Fuel Injection Cleaner 150 gr', category: Category.find(7)
Product.create! id: 14, code: 'DFS100', name: 'Diesel Purging System 100 ml', category: Category.find(11)
Product.create! id: 15, code: 'DFS400', name: 'Diesel Purging System 400 ml', category: Category.find(11)
Product.create! id: 16, code: 'AF300', name: 'Air Freshener', category: Category.find(12)
Product.create! id: 17, code: 'LB900', name: 'Drain Max 900 gr', category: Category.find(13)
